In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
class SelfAttention(nn.Module):
    def __init__(self, d_model):
        super(SelfAttention, self).__init__()
        self.W_q = torch.randn(d_model, d_model)
        self.W_k = torch.randn(d_model, d_model)
        self.W_v = torch.randn(d_model, d_model)

    def forward(self, x):
        Q = x @ self.W_q
        K = x @ self.W_k
        V = x @ self.W_v

        scores = Q @ K.T
        d_k = K.shape[-1]
        scaled_scores = scores / (d_k ** 0.5)

        attention_weights = F.softmax(scaled_scores, dim=-1)
        output = attention_weights @ V

        return output, attention_weights

In [14]:
x = torch.tensor([
    [1.0, 0.0, 1.0],   # Dog
    [0.0, 1.0, 1.0],   # Chasing
    [1.0, 1.0, 0.0]    # Cat
])

# Initialize model
attention = SelfAttention(d_model=3)

# Forward pass
output, weights = attention(x)

print("Input:\n", x)
print("\nAttention Weights:\n", weights)
print("\nOutput Representations:\n", output)

Input:
 tensor([[1., 0., 1.],
        [0., 1., 1.],
        [1., 1., 0.]])

Attention Weights:
 tensor([[0.2405, 0.6083, 0.1513],
        [0.0501, 0.4568, 0.4931],
        [0.7150, 0.1538, 0.1313]])

Output Representations:
 tensor([[-0.1924,  2.2300, -3.5344],
        [ 0.0299,  2.4532, -3.1282],
        [-0.4049,  1.3996, -4.2107]])
