In [1]:
import numpy as np

Step 1: Input Embeddings

In [2]:
X = np.array([
    [1, 0, 1],   # Dog
    [0, 1, 1],   # Chasing
    [1, 1, 0]    # Cat
])

print("Input Embeddings (X):\n", X)

Input Embeddings (X):
 [[1 0 1]
 [0 1 1]
 [1 1 0]]


Step 2: Weight Matrices

In [3]:
W_Q = np.eye(3)
W_K = np.eye(3)
W_V = np.eye(3)

Q = X @ W_Q
K = X @ W_K
V = X @ W_V

Step 3: Calculate Attention Scores

In [4]:
scores = Q @ K.T
print("Attention Scores:\n", scores)

Attention Scores:
 [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


Step 4: Scaling + Softmax

In [5]:
d_k = K.shape[1]
scaled_scores = scores / np.sqrt(d_k)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

attention_weights = softmax(scaled_scores)
print("\nAttention Weights (after softmax):\n", attention_weights)


Attention Weights (after softmax):
 [[0.47108308 0.26445846 0.26445846]
 [0.26445846 0.47108308 0.26445846]
 [0.26445846 0.26445846 0.47108308]]


Step 5: Final Output

In [7]:
output = attention_weights @ V
print("Final Output (New Representations):\n", output)

Final Output (New Representations):
 [[0.73554154 0.52891692 0.73554154]
 [0.52891692 0.73554154 0.73554154]
 [0.73554154 0.73554154 0.52891692]]
